# Generated by Django 4.2.7 on 2025-08-25 09:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('data_collection', '数据采集'), ('full_analysis', '完整分析'), ('alert_check', '告警检查')], default='data_collection', max_length=20, verbose_name='任务类型')),
                ('frequency', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], default='daily', max_length=10, verbose_name='执行频率')),
                ('hour', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='执行小时 (0-23)')),
                ('minute', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='执行分钟 (0-59)')),
                ('weekday', models.IntegerField(blank=True, help_text='仅当频率为每周时有效', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='星期几 (0=Monday)')),
                ('day_of_month', models.IntegerField(blank=True, help_text='仅当频率为每月时有效', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='月份中的第几天')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('skip_notifications', models.BooleanField(default=False, verbose_name='跳过通知')),
                ('retry_count', models.IntegerField(default=3, verbose_name='失败重试次数')),
                ('timeout_minutes', models.IntegerField(default=30, verbose_name='超时时间(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('app', models.ForeignKey(blank=True, help_text='不指定则对所有活跃App执行', null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.app', verbose_name='关联App')),
            ],
            options={
                'verbose_name': '任务调度',
                'verbose_name_plural': '任务调度',
                'ordering': ['hour', 'minute', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('scheduled', '定时触发'), ('manual', '手动触发'), ('retry', '重试执行')], default='scheduled', max_length=10, verbose_name='触发方式')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('timeout', '超时'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='执行状态')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='目标日期')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='执行时长(秒)')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功处理数量')),
                ('error_count', models.IntegerField(default=0, verbose_name='失败处理数量')),
                ('alerts_generated', models.IntegerField(default=0, verbose_name='生成告警数量')),
                ('notifications_sent', models.IntegerField(default=0, verbose_name='发送通知数量')),
                ('output_log', models.TextField(blank=True, verbose_name='执行日志')),
                ('error_log', models.TextField(blank=True, verbose_name='错误日志')),
                ('retry_count', models.IntegerField(default=0, verbose_name='已重试次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.app', verbose_name='执行App')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.taskschedule', verbose_name='任务调度')),
            ],
            options={
                'verbose_name': '任务执行记录',
                'verbose_name_plural': '任务执行记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
